### PR TITLE
Toolbar fix

### PR DESCRIPTION
**Pull request by steoo**
Introduced a new control trying to fix the issue #430

### CODE REVIEW

**Comment by daviferreira** [comment]
Hey @steoo, seems like there are some small linting problems. You can try to see that by running ```npm instal```  and then ```grunt js``` on your machine or check the Travis build feedback: https://travis-ci.org/daviferreira/medium-editor/builds/51075197

Let me know if you need any extra help!

**Comment by steoo** [comment]
Going to check out ;)

**Comment by steoo** [comment]
Updated, check it out :)

**Comment by daviferreira** [comment]
Gret work :)

I just added a verification to see if selection has range (382369fea0f7ca409814d98e271140bc60415cde).

**Comment by steoo** [comment]
Awesome! I updated through bower but the js in dist seems to be un-changed. Does it take some time to update? :)

**Comment by nchase** [comment]
hey @steoo, the default grunt task (i.e. just run `grunt`) should generate an updated dist file.

**Comment by steoo** [comment]
@nchase strange fact; I uninstalled and re-installed through NPM but still getting the old package (also in src/js)

**Comment by daviferreira** [comment]
@steoo did you update medium-editor version on your package.json?

**Comment by steoo** [comment]
yes, actually I used to use bower, but it gave me the same issue, tried  with npm (in which there wasn't the package ) and still getting the old one. In my package.json it says 

````
   depencies : {
      ...
      "medium-editor": "^2.4.5"
   }
````

**Comment by daviferreira** [comment]
@steoo can you try now with 2.4.6 please? Apparently there was indeed something wrong with our previous version.

**Comment by steoo** [comment]
Ok, this is working now. Thanks a lot, I was getting mad, thought was my fault :)

**Pull request merged**
