### PR TITLE
Add SauceLabs Configuration

### LINKED ISSUE #386: Get Saucelabs Working for medium-editor
@daviferreira @nmielnik and anyone else, here's what I'm thinking:

First mentioned in #370. We should be able to get feedback on how medium-editor works in different browsers.

The [medium-editor/try-saucelabs-configuration](https://github.com/daviferreira/medium-editor/tree/try-saucelabs-configuration) branch is my first cut at this issue.

So far the branch is connecting and reporting to Sauce Labs whenever a Travis CI build is kicked off. Sauce is running tests for Mac and Windows in Safari, Chrome, Firefox, and IE11.

Here's what we still need to do:
- [x] Investigate/agree on some account to use for the Sauce Labs reports. Currently it's linked to my personal Sauce Labs account which is almost definitely not what we will want to do.
- [x] Make the tests work fairly well in all browsers (a few failures is OK, so long as they make sense and either report known issues and/or we can fix them up fairly reliably)
- [x] Report test result details to sauce (e.g. via the "Jasmine JS Reporter" mentioned [here](https://github.com/axemclion/grunt-saucelabs#test-result-details-with-jasmine))

### PR DESCRIPTION
**Pull request by nchase**
Resolves #386 :smile_cat:

### CODE REVIEW

**Comment by nmielnik** [comment]
:smiley: :boom: :confetti_ball: :exclamation:

**Comment by sauravkhdoolia** [comment]
@nmielnik Sauce-Labs isn't working anymore.

I want to get it to work, So our build passes and we can focus on other issues. But

1. I dont know anything about Sauce Labs.
2. It's not working since a commit from you(Just a ref)
3. Help!!!

I think the account which was set up for medium editor is down or something, but off course I can't access that.

Thoughts?

**Comment by nmielnik** [comment]
@sauravkhdoolia I was able to find the saucelabs credentials, but it looks like saucelabs has done enough updates to blow away almost everything in the account, which is almost definitely why the saucelabs tests aren't running anymore.  

Also, the account is associated with an email address (mediumeditor@outlook.com) that I don't have access to and can't reset any more.

So first, you should make a shared email address to use for saucelabs that the group can access.

And then I see 2 options:
1. I can give you the credentials to the current account, and you can update the email address in there (there isn't much of anything in that account though)
2. You can create a new saucelabs account from scratch and use it for this repo.

Let me know.

**Comment by sauravkhdoolia** [comment]
Okay, So they have a Open Source program.

If we're already registered then we probably can't opt in for another account so we have to access the creds of previous account.

But if we were not, then I'd create a new account and do what's required to get those tests passing. 

Till then do you think that turning those tests off and merging some PRs which had all tests passing is a good idea!

Thanks for fast reply. Also I followed you on twitter, do you think that's a platform to ask you some questions rather than putting everything here in comments. 

I'd try to ensure much much less time is taken from you.

Thanks again.

**Comment by nmielnik** [comment]
I'd recommend Gitter actually, as it has a history of our internal discussions about the repo too. I invited you into Gitter and the private channel, let me know if you didn't get the invite.

**Pull request merged**
