### PR TITLE
Create Util.key to return key code from an event

### PR DESCRIPTION
**Pull request by j0k3r**
Instead of always trying to find which key is associated to an event for all browsers, I created a helper in Util to return this key.

I follow what is already done by jQuery.

It'll ease the transition when the `.key` will be compatible with all browsers (https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key)

Are you all ok with the `Util.key(event)` name ? Or should we use `Util.keyCode(event)` ?

### CODE REVIEW

**Comment by daviferreira** [comment]
I prefer keyCode :)

**Comment by j0k3r** [comment]
Well, it can't be `keyCode`, since `Util.keyCode` is already in use :cry: 

```
keyCode: {
    BACKSPACE: 8,
    TAB: 9,
    ENTER: 13,
    ESCAPE: 27,
    SPACE: 32,
    DELETE: 46
},
```

**Comment by daviferreira** [comment]
Time to create a constants file? :dancer: My beef with `key` is that it may lead to confusion with getting a property name etc. We can go like this now if you want.

**Comment by j0k3r** [comment]
Yeah good point.
We can wait for @nmielnik suggestion :smile: 

What about `getKeyCode`? But won't this be confusing with the `keyCode` constant?

**Comment by nmielnik** [comment]
I don't mean to add yet another opinion, but what about changing the helper to be something like:
`Util.isKey()` and having it take both a single KeyCode or an array of KeyCodes.

```javascript
  // case 1
  if (Util.isKey(event, Util.keyCode.ENTER)) {
    // cunning logic
  }

  // case 2
  if (Util.isKey(event, [Util.keyCode.DELETE, Util.keyCode.BACKSPACE])) {
    // fancy moves
  }
```

**Comment by j0k3r** [comment]
I like that :+1:

**Comment by nmielnik** [comment]
It kills that one case-switch, but I'm ok with that if you guys are

**Comment by daviferreira** [comment]
:+1:

**Pull request merged**
