### PR TITLE
Extension removeformat

### PR DESCRIPTION
**Pull request by phiggins42**
refs #505

### CODE REVIEW

**Comment by daviferreira** [comment]
Nice stuff :+1:

**Comment by daviferreira** [comment]
P.S. They are

**Comment by phiggins42** [comment]
hmm, looks like this breaks the ie's :/

**Comment by nmielnik** [comment]
Yeah, one of the joys of contenteditable is when you start adding attributes (`id`, `style`, etc.) into HTML elements inside a contenteditable, IE will generally never actually remove that element.

Generally to workaround things like this, we try to use a regex in the test case, assuming the result from various browsers is still valid.

I'm looking into fixing this so we can cut another release.

**Comment by steoo** [comment]
I made this gist, check it out
https://gist.github.com/steoo/6aa45e6c6d99974fbd2d

**Pull request merged**
