### PR TITLE
Add pasteReplacements options for custom RegExps

### PR DESCRIPTION
**Pull request by Sergiy-Babich**
https://github.com/daviferreira/medium-editor/issues/529

### CODE REVIEW

**Comment by nmielnik** [comment]
This is good stuff, do you mind updating README.md about this new option?

**Comment by phiggins42** [comment]
ideally, before introducing this as a public config we might take steps to breaking out config values into the groups (eg: 'paste': { replacements:[ ... ] }) or something?

**Comment by nmielnik** [comment]
Yeah, @Sergiy-Babich seems like this as well as #530 could be combined into a single option group like

```js
var editor = new MediumEditor('.editor', {
    paste: {
        cleanReplacements: [ ... ],
        cleanAttrs: [ ... ],
        cleanTags: [ ... ]
    }
}
```

That would be a good start and a clean way to, and should be pretty close to where we land with the overall options changes @phiggins42 has proposed.

**Comment by phiggins42** [comment]
yah if we introduce new config props as newly-grouped-type-things we have to deprecate less as we move others to the groupings.

**Comment by nmielnik** [comment]
This should now be supported as part of the changes for #535.  If you need additional support please propose another PR or open an issue.

Thanks for bringing this up!

**Pull request closed without merging**
