### PR TITLE
Add clean up options to pasteHTML

### PR DESCRIPTION
**Pull request by daviferreira**

### CODE REVIEW

**Comment by nmielnik** [comment]
Looks like firefox and ie are inserting a `<br>` after the end of the `<table>` tag for some reason...

**Comment by daviferreira** [comment]
Firefox tests are actually really intermitent on my machine

**Comment by daviferreira** [comment]
```
Content TestCase should removing paragraphs when a list is inserted inside of it
[Exception... "Failure" nsresult: "0x80004005 (NS_ERROR_FAILURE)" location: "JS frame :: file:///home/daviferreira/Projects/medium-editor/.grunt/grunt-contrib-jasmine/src/js/core.js :: execActionInternal :: line 9" data: no] thrown (line 9)


execActionInternal@file:///home/daviferreira/Projects/medium-editor/.grunt/grunt-contrib-jasmine/src/js/core.js:9:21621
MediumEditor.prototype.execAction@file:///home/daviferreira/Projects/medium-editor/.grunt/grunt-contrib-jasmine/src/js/core.js:9:31672
@file:///home/daviferreira/Projects/medium-editor/spec/content.spec.js:207:8
attemptSync@file:///home/daviferreira/Projects/medium-editor/.grunt/grunt-contrib-jasmine/jasmine.js:1741:8
QueueRunner.prototype.run@file:///home/daviferreira/Projects/medium-editor/.grunt/grunt-contrib-jasmine/jasmine.js:1729:8
QueueRunner.prototype.execute@file:///home/daviferreira/Projects/medium-editor/.grunt/grunt-contrib-jasmine/jasmine.js:1714:4
Env/queueRunnerFactory@file:///home/daviferreira/Projects/medium-editor/.grunt/grunt-contrib-jasmine/jasmine.js:608:6
Spec.prototype.execute@file:///home/daviferreira/Projects/medium-editor/.grunt/grunt-contrib-jasmine/jasmine.js:346:0
wrapChildAsAsync/<.fn@file:///home/daviferreira/Projects/medium-editor/.grunt/grunt-contrib-jasmine/jasmine.js:2059:36
attemptAsync@file:///home/daviferreira/Projects/medium-editor/.grunt/grunt-contrib-jasmine/jasmine.js:1771:8
QueueRunner.prototype.run@file:///home/daviferreira/Projects/medium-editor/.grunt/grunt-contrib-jasmine/jasmine.js:1726:8
attemptAsync/next<@file:///home/daviferreira/Projects/medium-editor/.grunt/grunt-contrib-jasmine/jasmine.js:1753:10
once/<@file:///home/daviferreira/Projects/medium-editor/.grunt/grunt-contrib-jasmine/jasmine.js:1697:8
complete@file:///home/daviferreira/Projects/medium-editor/.grunt/grunt-contrib-jasmine/jasmine.js:2054:8

**Comment by nmielnik** [comment]
Yeah, myself and @patrick-webs have seen this failure locally as well.  I had started looking into it at one point, though I seemed to have forgotten about it.

For whatever reason, this doesn't happen in saucelabs, so it hasn't been a high priority.

I've run into this issue a lot with firefox, where trying to simulate actual user interaction with selection and `document.execCommand()` causes firefox to throw the `NS_ERROR_FAILURE` error.  It's frustrating because those errors are just because we're running tests, if you actually mimic the test tests manually through a browser, you'll never get that error...

**Comment by daviferreira** [comment]
Only getting errors on FF when console is not open :sob:

**Comment by nmielnik** [comment]
Don't worry about the FF issues for now, they aren't happening in saucelabs so we can fix them later.

I think I found the issue in IE, seems like if you select the entire contentedtiable `<div>`, when our fallback code for `insertHTML` runs, it doesn't actually paste the contents in.  Instead, if you make the selection contain just the 'hhh' text node, everything seems to work ok.

I'll push up the fix.

**Comment by nmielnik** [comment]
@daviferreira I got the tests to pass for IE, and I added another test case I thought we be useful (for verifying the defaults for `pasteHTML` are still working).

Cool feature dude :sunglasses:

**Comment by daviferreira** [comment]
:+1: 

Maybe we should get Linux on SauceLabs? :penguin:

**Pull request merged**
