### PR TITLE
jscs

### PR DESCRIPTION
**Pull request by daviferreira**

### CODE REVIEW

**Comment by nchase** [comment]
:smirk: I like where this is heading

**Comment by nchase** [comment]
I know the project is fairly deeply-invested in Grunt as a tool for handling the processes that the library needs to undergo, but have you considered just using the JSCS binary? Its [options](http://jscs.info/overview.html) will let you configure all of the things you're interested in.

Travis will know how to deal with the output – both use standard unix exit code to signal errors.

**Comment by nmielnik** [comment]
I think I need spellcheck for commit messages :disappointed:

**Comment by daviferreira** [comment]
@nchase sure, but why not use grunt for consistency? Unless we move everything away from it.. I'm game :dancers:

**Pull request merged**
