### PR TITLE
Add spellcheck options to enable/disable native spellcheck

### PR DESCRIPTION
**Pull request by daviferreira**
I find the red underlining really annoying :smile:

### CODE REVIEW

**Comment by nmielnik** [comment]
Are you sure it should be disabled by default?

**Comment by daviferreira** [comment]
I don't mind, anything will do for me, I just want to be able to disable it.

**Comment by nmielnik** [comment]
:beers: now if only it didn't break in pretty much every browser.  Funny, I didn't peg you for a safari user :smiley:

**Comment by daviferreira** [comment]
Hahaha, actually using Opera...

**Comment by nmielnik** [comment]
Opera

**Comment by daviferreira** [comment]
Is it me or SL now?

**Comment by nmielnik** [comment]
Yeah, they seem to be slow...but all the tests pass once things eventually complete in sauce lab...

**Pull request merged**
